Added support for new event generation in ruby code
logstash-plugins/logstash-filter-aggregate pull request #116
Opened 2021-09-17 13:06 UTC by rocco8620

Hello,
This PR adds support for new event generation in the ruby code executed for every event processed by the aggregate plugin.
It uses the same logic as the `ruby` filter plugin.

2021-09-18 09:04 UTC, fbaligand commented
Hi @rocco8620,

First thanks for your contribution to this plugin!

Then some remarks:
- could you sign Contributor Agreement, as mentioned in [cla-checker-service comment](#issuecomment-921781984) ?
- could you add some usage documentation about this in [docs/index.asciidoc](https://github.com/logstash-plugins/logstash-filter-aggregate/blob/master/docs/index.asciidoc), in the same way than [ruby filter documentation](https://www.elastic.co/guide/en/logstash/current/plugins-filters-ruby.html#plugins-filters-ruby-using-inline-script). I think that it would be fine to put this doc into [`code` option section](https://github.com/logstash-plugins/logstash-filter-aggregate/blob/master/docs/index.asciidoc#plugins-filters-aggregate-code)
- could you add one unit test for this feature [here](https://github.com/logstash-plugins/logstash-filter-aggregate/blob/master/spec/filters/aggregate_spec.rb)?

2021-09-20 13:13 UTC, rocco8620 commented
Hello,
thank you for the pointers.

I have tried to sign the agreement before doing the previous commit, but it still shows as unsigned. Have you got any tips about that?
I have added some documentation and a test, let me know if i should add more. I am not fluent in ruby and less so with rspec. 
 
Thank you

2021-09-21 22:23 UTC, fbaligand commented
Hi,

Thanks for this new commit!

my remarks :
- concerning agreement signature, you could see that [cla-checker-service comment](#issuecomment-921781984) has been edited and now references only your last commit. And your last commit has for author: "Rocco Mancin" (not rocco8620). So I think signature agreement is OK for rocco8620, but not for "Rocco Mancin" that is not a GitHub user. So I invite your to rewrite this commit with rocco8620 account and force PR update.
- concerning the test, it is exactly what I expected! This is nice and Travis CI build is OK.
- concerning the documentation:
  - first could you add `new_event_block` to variables list in `code` setting?
  - could you fix the little typos that I suggested directly on file
  - could you restore _" When option push_map_as_event_on_timeout=true, if you set `map_meta.timeout=0` in `code` block, then aggregated map is immediately pushed as a new event."_ sentence where it was before? I mean just before first example.

Thanks in advance!

2021-09-22 07:47 UTC, rocco8620 commented
Hello, 
I have applied the changes. Let me know if it is all good.
Thank you

2021-09-24 07:50 UTC, fbaligand commented
Hi @rocco8620,

I just did a last review on documentation and suggested few changes.
Once it's done, your PR will be ready to be merged!

Fabien

2021-09-24 10:02 UTC, rocco8620 commented
Hello,
Sadly, I don't see any suggested change on the PR.

R.

2021-09-24 12:37 UTC, rocco8620 commented
This is what i see on that page:

![Screenshot from 2021-09-24 14-28-41](https://user-images.githubusercontent.com/15247796/134674476-768e1c22-8083-4430-9b01-7325c18b0673.png)

2021-09-25 10:17 UTC, fbaligand requested changes
Could you just apply my few documentation suggestions?

2021-09-25 10:23 UTC, fbaligand commented
@rocco8620 
I realized that I had to explicitly apply my review so that you see my suggested changes. 
so now, do you see them?

2021-09-27 10:46 UTC, rocco8620 commented
Hello,
I have merged the suggested changes.
R.

2021-09-28 07:32 UTC, fbaligand approved these changes

2021-09-28 07:33 UTC, fbaligand commented
This is OK for me!
LGTM!

2021-09-28 07:37 UTC, merged

2021-09-28 07:38 UTC, fbaligand commented
Thanks again for your contribution to this plugin!
I will release it soon with this new feature.

2021-09-28 09:02 UTC, rocco8620 commented
@fbaligand Thank you!